apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: kimai-ingress
spec:
  rules:
  - host: web.kimai.com
    http:
      paths:
      - backend:
          serviceName: kimai-service
          servicePort: 8081
        path: /
